/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { GeniusDiamond, GeniusDiamondInterface } from "../GeniusDiamond";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256[]",
        name: "tokenIds",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "addresses",
        type: "address[]",
      },
    ],
    name: "AddToBlackList",
    type: "event",
    _diamondFacet: "GNUSControl",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "bannedAddress",
        type: "address",
      },
    ],
    name: "AddToGlobalBlackList",
    type: "event",
    _diamondFacet: "GNUSControl",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "Approval",
    type: "event",
    _diamondFacet: "GNUSBridge",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "approved",
        type: "bool",
      },
    ],
    name: "ApprovalForAll",
    type: "event",
    _diamondFacet: "GNUSNFTFactory",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "srcChainID",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "destChainID",
        type: "uint256",
      },
    ],
    name: "BridgeSourceBurned",
    type: "event",
    _diamondFacet: "GNUSBridge",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "initializer",
        type: "string",
      },
    ],
    name: "InitLog",
    type: "event",
    _diamondFacet: "DiamondInitFacet",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
    _diamondFacet: "GeniusOwnershipFacet",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Paused",
    type: "event",
    _diamondFacet: "GNUSNFTFactory",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256[]",
        name: "tokenIds",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "addresses",
        type: "address[]",
      },
    ],
    name: "RemoveFromBlackList",
    type: "event",
    _diamondFacet: "GNUSControl",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "bannedAddress",
        type: "address",
      },
    ],
    name: "RemoveFromGlobalBlackList",
    type: "event",
    _diamondFacet: "GNUSControl",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "previousAdminRole",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "newAdminRole",
        type: "bytes32",
      },
    ],
    name: "RoleAdminChanged",
    type: "event",
    _diamondFacet: "GeniusOwnershipFacet",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleGranted",
    type: "event",
    _diamondFacet: "GeniusOwnershipFacet",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleRevoked",
    type: "event",
    _diamondFacet: "GeniusOwnershipFacet",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
    _diamondFacet: "GNUSBridge",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "ids",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "values",
        type: "uint256[]",
      },
    ],
    name: "TransferBatch",
    type: "event",
    _diamondFacet: "GNUSNFTFactory",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address[]",
        name: "destinations",
        type: "address[]",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "values",
        type: "uint256[]",
      },
    ],
    name: "TransferBatch",
    type: "event",
    _diamondFacet: "ERC20TransferBatch",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "TransferSingle",
    type: "event",
    _diamondFacet: "GNUSNFTFactory",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Unpaused",
    type: "event",
    _diamondFacet: "GNUSNFTFactory",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "newFee",
        type: "uint256",
      },
    ],
    name: "UpdateBridgeFee",
    type: "event",
    _diamondFacet: "GNUSControl",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "value",
        type: "string",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "URI",
    type: "event",
    _diamondFacet: "GNUSNFTFactory",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "WithdrawToken",
    type: "event",
    _diamondFacet: "GNUSContractAssets",
  },
  {
    inputs: [],
    name: "CannotWithdrawGNUS",
    type: "error",
    _diamondFacet: "GNUSContractAssets",
  },
  {
    inputs: [],
    name: "ErrorWithdrawingEther",
    type: "error",
    _diamondFacet: "GNUSContractAssets",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "spender",
        type: "address",
      },
    ],
    name: "allowance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GNUSBridge",
    _diamondSelector: "0xdd62ed3e",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "tokenIds",
        type: "uint256[]",
      },
      {
        internalType: "address[]",
        name: "bannedAddresses",
        type: "address[]",
      },
    ],
    name: "allowTransferorBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSControl",
    _diamondSelector: "0x9e8e7134",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "bannedAddress",
        type: "address",
      },
    ],
    name: "allowTransferorForAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSControl",
    _diamondSelector: "0x9ceb1593",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "approve",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSBridge",
    _diamondSelector: "0x095ea7b3",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0x00fdd58e",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GNUSBridge",
    _diamondSelector: "0x70a08231",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "accounts",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "ids",
        type: "uint256[]",
      },
    ],
    name: "balanceOfBatch",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0x4e1273f4",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "tokenIds",
        type: "uint256[]",
      },
      {
        internalType: "address[]",
        name: "bannedAddresses",
        type: "address[]",
      },
    ],
    name: "banTransferorBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSControl",
    _diamondSelector: "0x19a8b28a",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "bannedAddress",
        type: "address",
      },
    ],
    name: "banTransferorForAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSControl",
    _diamondSelector: "0x1307a4be",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "destChainID",
        type: "uint256",
      },
    ],
    name: "bridgeOut",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSBridge",
    _diamondSelector: "0xe26d65a6",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0xf5298aca",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSBridge",
    _diamondSelector: "0x9dc29fac",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "ids",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "values",
        type: "uint256[]",
      },
    ],
    name: "burnBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0x6b20c454",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "parentID",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "exchRate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "max_supply",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "newuri",
        type: "string",
      },
    ],
    name: "createNFT",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0xf667ab7c",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "parentID",
        type: "uint256",
      },
      {
        internalType: "string[]",
        name: "names",
        type: "string[]",
      },
      {
        internalType: "string[]",
        name: "symbols",
        type: "string[]",
      },
      {
        internalType: "uint256[]",
        name: "exchRates",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "max_supplies",
        type: "uint256[]",
      },
      {
        internalType: "string[]",
        name: "newuris",
        type: "string[]",
      },
    ],
    name: "createNFTs",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0x1a9d2360",
  },
  {
    inputs: [],
    name: "CREATOR_ROLE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0x8aeda25a",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "creators",
    outputs: [
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "ERC1155ProxyOperator",
    _diamondSelector: "0xcd53d08e",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GNUSBridge",
    _diamondSelector: "0x313ce567",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "subtractedValue",
        type: "uint256",
      },
    ],
    name: "decreaseAllowance",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSBridge",
    _diamondSelector: "0xa457c2d7",
  },
  {
    inputs: [],
    name: "DEFAULT_ADMIN_ROLE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GeniusOwnershipFacet",
    _diamondSelector: "0xa217fddf",
  },
  {
    inputs: [],
    name: "diamondInitialize250",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "DiamondInitFacet",
    _diamondSelector: "0xeae960b1",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "exists",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0x4f558e79",
  },
  {
    inputs: [],
    name: "GeniusAI_Initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GeniusAI",
    _diamondSelector: "0x6ea9fd36",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "getNFTInfo",
    outputs: [
      {
        components: [
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "symbol",
            type: "string",
          },
          {
            internalType: "string",
            name: "uri",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "exchangeRate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxSupply",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "creator",
            type: "address",
          },
          {
            internalType: "uint128",
            name: "childCurIndex",
            type: "uint128",
          },
          {
            internalType: "bool",
            name: "nftCreated",
            type: "bool",
          },
        ],
        internalType: "struct NFT",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0xd188929f",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
    ],
    name: "getRoleAdmin",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GeniusOwnershipFacet",
    _diamondSelector: "0x248a9ca3",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "getRoleMember",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GeniusOwnershipFacet",
    _diamondSelector: "0x9010d07c",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
    ],
    name: "getRoleMemberCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GeniusOwnershipFacet",
    _diamondSelector: "0xca15c873",
  },
  {
    inputs: [],
    name: "GNUSBridge_Initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSBridge",
    _diamondSelector: "0x5e3e0c59",
  },
  {
    inputs: [],
    name: "GNUSControl_Initialize230",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSControl",
    _diamondSelector: "0x72f6ac43",
  },
  {
    inputs: [],
    name: "GNUSNFTFactory_Initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0x101521f8",
  },
  {
    inputs: [],
    name: "GNUSNFTFactory_Initialize230",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0x52dbff7a",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "grantRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GeniusOwnershipFacet",
    _diamondSelector: "0x2f2ff15d",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "hasRole",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GeniusOwnershipFacet",
    _diamondSelector: "0x91d14854",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "addedValue",
        type: "uint256",
      },
    ],
    name: "increaseAllowance",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSBridge",
    _diamondSelector: "0x39509351",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "isApprovedForAll",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0xe985e9c5",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0x731133e9",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenID",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSBridge",
    _diamondSelector: "0x156e29f6",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSBridge",
    _diamondSelector: "0x40c10f19",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "ids",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "mintBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0x1f7fdffa",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "destinations",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    name: "mintBatch",
    outputs: [],
    stateMutability: "payable",
    type: "function",
    _diamondFacet: "ERC20TransferBatch",
    _diamondSelector: "0x7c88e3d9",
  },
  {
    inputs: [],
    name: "MINTER_ROLE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GNUSBridge",
    _diamondSelector: "0xd5391393",
  },
  {
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GNUSNFTCollectionName",
    _diamondSelector: "0x06fdde03",
  },
  {
    inputs: [],
    name: "NFT_PROXY_OPERATOR_ROLE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "ERC1155ProxyOperator",
    _diamondSelector: "0xa2dd2453",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "UUID",
        type: "bytes32",
      },
    ],
    name: "OpenEscrow",
    outputs: [],
    stateMutability: "payable",
    type: "function",
    _diamondFacet: "GeniusAI",
    _diamondSelector: "0x31d6388d",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "owner_",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GeniusOwnershipFacet",
    _diamondSelector: "0x8da5cb5b",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0x8456cb59",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0x5c975abb",
  },
  {
    inputs: [],
    name: "protocolInfo",
    outputs: [
      {
        internalType: "uint256",
        name: "bridgeFee",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "protocolVersion",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "chainID",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GNUSControl",
    _diamondSelector: "0x93420cf4",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "renounceRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GeniusOwnershipFacet",
    _diamondSelector: "0x36568abe",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "revokeRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GeniusOwnershipFacet",
    _diamondSelector: "0xd547741f",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "ids",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "safeBatchTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0x2eb2c2d6",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0xf242432a",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "bool",
        name: "approved",
        type: "bool",
      },
    ],
    name: "setApprovalForAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0xa22cb465",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "chainID",
        type: "uint256",
      },
    ],
    name: "setChainID",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSControl",
    _diamondSelector: "0xed8d47e6",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "protocolVersion",
        type: "uint256",
      },
    ],
    name: "setProtocolVersion",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSControl",
    _diamondSelector: "0xceba5598",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "newuri",
        type: "string",
      },
    ],
    name: "setURI",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0x02fe5305",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "newuri",
        type: "string",
      },
    ],
    name: "setURI",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0x862440e2",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GeniusOwnershipFacet",
    _diamondSelector: "0x01ffc9a7",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GNUSBridge",
    _diamondSelector: "0x95d89b41",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0xbd85b039",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GNUSBridge",
    _diamondSelector: "0x18160ddd",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSBridge",
    _diamondSelector: "0xa9059cbb",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "destinations",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    name: "transferBatch",
    outputs: [],
    stateMutability: "payable",
    type: "function",
    _diamondFacet: "ERC20TransferBatch",
    _diamondSelector: "0x3b3e672f",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSBridge",
    _diamondSelector: "0x23b872dd",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "destinations",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    name: "transferOrBurnBatch",
    outputs: [],
    stateMutability: "payable",
    type: "function",
    _diamondFacet: "ERC20TransferBatch",
    _diamondSelector: "0x1bdc02ba",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GeniusOwnershipFacet",
    _diamondSelector: "0xf2fde38b",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0x3f4ba83a",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newFee",
        type: "uint256",
      },
    ],
    name: "updateBridgeFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSControl",
    _diamondSelector: "0x5a1c0366",
  },
  {
    inputs: [],
    name: "UPGRADER_ROLE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GeniusOwnershipFacet",
    _diamondSelector: "0xf72c0d8b",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "uri",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "GNUSNFTFactory",
    _diamondSelector: "0x0e89341c",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSBridge",
    _diamondSelector: "0x441a3e70",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdrawToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "GNUSContractAssets",
    _diamondSelector: "0x01e33667",
  },
] as const;

export class GeniusDiamond__factory {
  static readonly abi = _abi;
  static createInterface(): GeniusDiamondInterface {
    return new Interface(_abi) as GeniusDiamondInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): GeniusDiamond {
    return new Contract(address, _abi, runner) as unknown as GeniusDiamond;
  }
}
