/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GeniusDiamond } from "./GeniusDiamond";
export * as factories from "./factories";
export { GeniusDiamond__factory } from "./factories/GeniusDiamond__factory";
